### PR TITLE
Allow different image sets to be displayed

### LINKED ISSUE #5: Allow to choose different background images present in the same folder as a plant 3D reconstruction (raw scan pics, binarized images, undistorted images, fake backgrounds for virtual plants, etc...)
#BetterPlantVis

### PR DESCRIPTION
**Pull request by Raphalex46**
Close #5

### CODE REVIEW

**Review by fabfabBesnard — CHANGES_REQUESTED** [review]
the Visualizer crashes when a scan is opened
image

Error log:
```
areHookInputsEqual
node_modules/babel-loader/lib/index.js??ref--6-oneOf-2!/home/fabfab/softwares/romi/Visualiser/Raph_branches/3d-plantviewer-images/node_modules/react-dom/cjs/react-dom.development.js:13322
  13319 | {
  13320 |   // Don't bother comparing lengths in prod because these arrays should be
  13321 |   // passed inline.
> 13322 |   if (nextDeps.length !== prevDeps.length) {
        | ^  13323 |     warning$1(false, 'The final argument passed to %s changed size between renders. The ' + 'order and size of this array must remain constant.\n\n' + 'Previous: %s\n' + 'Incoming: %s', currentHookNameInDev, '[' + nextDeps.join(', ') + ']', '[' + prevDeps.join(', ') + ']');
  13324 |   }
  13325 | }
View compiled
updateMemo
node_modules/babel-loader/lib/index.js??ref--6-oneOf-2!/home/fabfab/softwares/romi/Visualiser/Raph_branches/3d-plantviewer-images/node_modules/react-dom/cjs/react-dom.development.js:13896
  13893 | if (nextDeps !== null) {
  13894 |   var prevDeps = prevState[1];
  13895 | 
> 13896 |   if (areHookInputsEqual(nextDeps, prevDeps)) {
        | ^  13897 |     return prevState[0];
  13898 |   }
  13899 | }
View compiled
useMemo
node_modules/babel-loader/lib/index.js??ref--6-oneOf-2!/home/fabfab/softwares/romi/Visualiser/Raph_branches/3d-plantviewer-images/node_modules/react-dom/cjs/react-dom.development.js:14161
  14158 | ReactCurrentDispatcher$1.current = InvalidNestedHooksDispatcherOnUpdateInDEV;
  14159 | 
  14160 | try {
> 14161 |   return updateMemo(create, deps);
        | ^  14162 | } finally {
  14163 |   ReactCurrentDispatcher$1.current = prevDispatcher;
  14164 | }
View compiled
useMemo
node_modules/babel-loader/lib/index.js??ref--6-oneOf-2!/home/fabfab/softwares/romi/Visualiser/Raph_branches/3d-plantviewer-images/node_modules/react/cjs/react.development.js:1525
  1522 | 
  1523 | function useMemo(create, inputs) {
  1524 |   var dispatcher = resolveDispatcher();
> 1525 |   return dispatcher.useMemo(create, inputs);
       | ^  1526 | }
  1527 | 
  1528 | function useImperativeHandle(ref, create, inputs) {
View compiled
useImageSet
src/flow/scans/accessors.js:118:2
  115 |     [scans]
  116 |   )
  117 | 
> 118 |   return [enhancedScans]
      |  ^  119 | }
  120 | 
  121 | export const useSearchQuery = useAccessor(
View compiled
Carousel
src/Viewer/Carousel/index.js:147:19
  144 | 
  145 | useEffect(
  146 |   () => {
> 147 |     if (context) {
      |                 ^  148 |       const { width, height } = getSize(containerRef.current)
  149 |       sizes = {
  150 |         width,
View compiled
▶ 16 stack frames were collapsed.
eval
src/rd/tools/hooks/fetch.js:91:14
  88 | .catch((error) => {
  89 |   if (!unmounted) {
  90 |     console.log(error) // DEV
> 91 |     setError(new Error(error))
     |    ^  92 |     setLoading(false)
  93 |   }
  94 | })
View compiled
```

**Comment by Raphalex46** [comment]
I didn't see this bug because I didn't open a scan while working. I'm investigating the problem.

**Comment by fabfabBesnard** [comment]
The crash is fixed.
The new button appears, but there is no image in the carousel and the camera mode cannot be activated.
image

**Comment by Raphalex46** [comment]
Should be fixed now, try to review it (I hope) a last time.

**Comment by fabfabBesnard** [comment]
db "v0.5/13 plants" tested locally, I tried 3 plants randomly
everything is ok: raw + undistrorted + masks display normally in mode camera, overlay with 3D reconstructed data is nice.

I validate this new functionality ! thx !!

just one suggestion: change the camera logo for the option (not the same as for screen capture)

**Comment by Raphalex46** [comment]
Icon change is on the way ! I'll just make an issue to check for unavailable data. If there are no photos in the folder, the visualizer crashes.

**Comment by Raphalex46** [comment]
A new icon has been added.

**Comment by fabfabBesnard** [comment]
super, icône idéale, c'est explicite.
c'est tout bon !!
PR can be merged

**Pull request merged**
