### PR TITLE
Export plot csv / tsv with multiple options

### LINKED ISSUE #10: Export sequences in csv/tsv format
-for one plant
-for all selected plant of a list (main page)
#Export tools

### PR DESCRIPTION
**Pull request by Raphalex46**
This should be good for review, tsv format isn't available yet but is easy to implement. I'll make a new issue for tsv.

Close #10

### CODE REVIEW

**Comment by fabfabBesnard** [comment]
detail to change: on mouse over the blue download arrow, the text says "download MANUAL sequence" instead of "AUTOMATED" (for both charts).
Except this detail, all is working well: correct and please merge this branch !

**Comment by fabfabBesnard** [comment]
Suggestion for improvement:
-allow for csv / tsv formats
-make an export with both automated and manual data in the same file
-for divergence angles: choose either radian or degree

**Comment by Raphalex46** [comment]
I thought about the degrees / radians thing. I think I'll add the tsv, randians and both in same file in this pull request instead of merging this one

**Comment by Raphalex46** [comment]
I'm currently working on it, but I don't know how a CSV file with a different number of values on each column would work. I will make the radians and angles as well as the TSV format for the moment.

**Comment by Raphalex46** [comment]
Ok, this looks good to me, i'll leave an issue to clean up this code a bit though because it's not the prettiest in my opinion. Let me know if there is any bug I missed. I tried to make the switches visually pleasing, I hope this delivers.

**Comment by fabfabBesnard** [comment]
-For printing both automated & measured values on the same: it's true it is not really relevant because of different numbers of values and the absence of warranty that for a given idnex, values do correspond. Conclusion: keep a separated export
-small detail: manage the extensions: .csv or .tsv according to the format chosen (now it's always named .csv). Howover the format (comma or tab) is correctly implemented.

**Comment by fabfabBesnard** [comment]
this PR can be merged

**Review by fabfabBesnard — APPROVED** [review]

**Comment by Raphalex46** [comment]
Oops, I forgot about the extension, yes. I'll make that small fix and merge

**Pull request merged**
