### PR TITLE
Selection through view

### LINKED ISSUE #3: Give information on mouse click:
-organ N° / semantic label 
#BetterPlantVis

### PR DESCRIPTION
**Pull request by Raphalex46**
Close #3

### CODE REVIEW

**Comment by fabfabBesnard** [comment]
Great Raphaël. OK, I'll try to review this new function before Tomorrow.

**Comment by fabfabBesnard** [comment]
I also ask Jo about how building automatically new docker images at each new PR...

**Comment by Raphalex46** [comment]
This PR is just for displaying the info bubbles. I will make a new PR in the future to handle drag and drop of info bubbles, and the content of those isn't definitive either. We can later replace the content with anything, could even be images or things like that.

**Comment by Raphalex46** [comment]
I think I just noticed a problem with clicking on the very first organ. I'll check it a bit later, just think to test this during the review, i'll fix it accordingly

**Comment by fabfabBesnard** [comment]
I noticed two bugs:
-the indices are shifted by 1 (the selected organ has an index 1-unit below the right index)
image
-Clicking the organ is deactivated on the same organ after closing the bubble. It can be reactivated by clicking on another organ.
-clicking is not working when background images are displayed

Possible improvements:
-Fix bubble location in 3D so that it moves with the plant ?
-color the bubble with the same shade as the organ ?

**Comment by Raphalex46** [comment]
Thanks for the review

> clicking is not working when background images are displayed

That's the only bug that's 'intended', because the 'camera' and 'free roam' modes are treated differently in the code. I can work on refactoring to make this available in both modes if it's necessary.

Bubble location in 3d is something I thought about, and doesn't seem very easy to implement at first glance, I'll make some research as soon as possible to see what tools I can use to make this possible.

**Comment by Raphalex46** [comment]
I fixed the bugs and added the colored bubble. I think the other points like clicking when in camera mode and 3d bubbles should be discussed further.

**Comment by fabfabBesnard** [comment]
ok, bubble selection works well and indices are fine.

**Pull request merged**
