### PR TITLE
Seg edit

### LINKED ISSUE #81: (if semantic segmentation is available): correct errors in pcd / change a label
#edit PCD

### PR DESCRIPTION
**Pull request by Raphalex46**
Add multiple selection methods to modify labels of the segmented point cloud Close #81

### CODE REVIEW

**Review by fabfabBesnard — APPROVED** [review]
This first assay to implement a 'segmentation edition' works well (tested with one plant only)
This PR could be merged as it is.

But I have several remarks to improve further versions:
****bugs**
-the contextual menu choice "Make a custom selection from this point" does not work
-when I click only one point "Select this point", I cannot change the label

****improve**:
-It's hard to guess the selected point. Could you find a way to highlight the active point ? (bounding box/circle, pointing arrow or arrowhead, fill with hashes, ...
-Since there is a little freeze of the screen while it looks for close points with the same label, could it be possible to display something informing the user that computation is running ? (e.g: progress bar, turning wheel or rolling glasshour, "please wait" pop-up, etc....)
-Once the neighbouring points have been selected, the user do not know which they are. Could it be possible again to highlight the current selection ?
-make an "undo" function if user is not happy with the label edition ?
-Some few points are really hard to edit
ex: in the basal leaf of Col0_26_10_2018_B, I changed a large distal area that was labelled as fruit, but a few red points remains. I cannot edit them by clicking, although they look very close to each other:
image
Could the algo to find neighbouring points be improved ?

****Details**: 
-default colors for labels: I personaly find more intuitive to display leaves in green and pedicel not in green (e.g. something closer to fruit color -red-, such as yellow or orange)

**Comment by Raphalex46** [comment]
I don't understand the bugs because I didn't see any of them while testing, can you describe the process in more detail to see when these bugs appear ?

I already thought about the improvements you listed, I think that since this is a pretty big PR in itself, we should merge this one and create another for the improvements.

I know it's hard to see which point is clicked due to the size and number of the points, I don't think I can do anything significant to improve that behavior in the time that I'm given.

For the colors, this is not really possible since the code for the segmented point cloud isn't supposed to know the semantic meaning of the labels. The colors are given arbitrarily between every label and made to be as different from each other as possible. I'm afraid that "forcing" colors on specific labels will make readability more difficult in plants that have a lot of labels. But you can always change the color of the legend yourself if you want green leaves, that's what it's made for.

**Comment by fabfabBesnard** [comment]
I agree with all your comments: merge this PR and keep improvements for future commits.
I understand for the default color: it's not a big issue anyway.

Concerning the bugs:
-**the contextual menu choice "Make a custom selection from this point" does not work**
when I click, nothing happen
-**when I click only one point "Select this point", I cannot change the label**
when I click on a point and choose "select this point", the next menu pops out (new label) but nothing happen when I ask for a label change (I zoomed at amximum on a point to be sure of the point I was selecting, but I could never change its label)

**Comment by Raphalex46** [comment]
For the single point bug, I think it just changed the label of a point you can't see

**Comment by Raphalex46** [comment]
I checked the bugs you mentioned but everything worked fine for me. When you click on "make a custom selection", by moving the mouse on points, you will see a sphere that represents the selection, and you can confirm the selection by left clicking. Maybe it needs to be easier for the user ?

**Pull request merged**
