### PR TITLE
Add fully functional segmented point cloud

### LINKED ISSUE #62: (if semantic labels available) -> allow color by type of semantic labels
#BetterPlantVis

### LINKED ISSUE #74: Update scan list to add segmented point cloud info
Add filters and icons for segmented point cloud availability.

### PR DESCRIPTION
**Pull request by Raphalex46**
Close #62

### CODE REVIEW

**Comment by Raphalex46** [comment]
This commit history looks messy, but it's very clean ! A few force push were necessary to put everything in order, that's all.

This PR will only work correctly with [this PR](https://github.com/romi/romidata/pull/36) merged into romidata.

The last update to this PR closes #74

**Comment by Raphalex46** [comment]
Let me know if there is any significant performance loss or issue. The scan should take a bit longer than normal to load initially, but the experience afterwards should be unchanged. When customizing the color of each label in the segmented point cloud, the colors will be refresh only half a second later. This is to prevent rewriting thousands of values everytime you change color to avoid overloading the CPU for no reason. This delay shouldn't be a problem in any way.

**Review by fabfabBesnard — COMMENTED** [review]
Crash report !!
I tested this PR with:
-output data from geom pipe -> it's OK: the new icon for "segmented pcd" appears, but of course no data is available to be displayed
-output data from ML pipe (the 3 plants given by Jo the 26/06/2020). The scan list uploads, but on 'availle data', it says that segmented pcd are absent from the three folders. Then, when selecting a reconstruction, it crashes immediately while trying to display data.
```
TypeError: Cannot read property 'forEach' of undefined
new Angles
src/Viewer/World/entities/angles.js:74:10
  71 |     resolution: { x: window.innerWidth, y: window.innerHeight }
  72 |   })
  73 | )
> 74 | obj.raycast = LineRaycast
     |    ^  75 | obj.defaultColor = color
  76 | obj.customColor = null
  77 | obj.computeLineDistances()
View compiled
World.setAnglesPoints
src/Viewer/World/object.js:430:13
  427 |   if (this.segmentedPointCloud) this.segmentedPointCloud.setVisible(layers.segmentedPointCloud)
  428 |   if (this.skeleton) this.skeleton.setVisible(layers.skeleton)
  429 |   if (this.anlesPoints) this.anlesPoints.setVisible(layers.angles)
> 430 |   if (this.CameraPointsGroup) this.CameraPointsGroup.visible = layers.cameras
      |           ^  431 | }
  432 | 
  433 | takeSnapshot (size) {
View compiled
eval
src/Viewer/World/index.js:380:9
  377 |   [world, mouse]
  378 | )
  379 | 
> 380 | return <Container ref={containerRef}>
      |       ^  381 |   <CanvasContainer
  382 |     ref={canvasRef}
  383 |     onMouseDown={eventFns.onMouseDown}
View compiled
▶ 9 stack frames were collapsed.
eval
src/rd/tools/hooks/fetch.js:75:8
  72 | } else {
  73 |   setData(null)
  74 |   setLoading(true)
> 75 |   source = CancelToken.source()
     |  ^  76 |   const fetchResource = forgeFetchResource(url, source, options)
  77 | 
  78 |   if (cached) cache[url] = fetchResource
View compiled
```
One doubt: do I have all data in the scans I'm testing ?
in the visualizer subfolder, there is '`PointCloud.ply`', but it is not segmented (checked by opening with Meshlab). Note that in the `SegmentedPointCloud_out__Segmentation2D_hash` folder however, there is the segmented point cloud (`SegmentedPointCloud.ply`, which do appear segmented with meshlab), but replacing this file in the Visualisation folder does not solve the crash, nor the recognition in the scan list

**Comment by Raphalex46** [comment]
This is the bug I mentionned last time. The visualizer tries to load angle data but there isn't any `fruit_points` in `AnglesAndInternodes.json`.

Since I couldn't get a functionnal scan, I replaced the `AnglesAndInternodes.json` of the three scans from Jo by a valid one.

Try to do that and it shouldn't crash anymore. Try to contact Jo for valid scans for the future maybe ?

**Comment by fabfabBesnard** [comment]
I'm so stupid. Of course that's the same issue again ! What is your valid `AnglesAndInternodes.json` file ? You take this file from a random plant or you take the file generated on the same plant by the geom pipe ?

**Comment by Raphalex46** [comment]
I took a random file that works from another plant. The point is just to open the scan without crashing, simply hide the organs layer.

**Comment by fabfabBesnard** [comment]
Ok, I tried this time to replace `Visualisation/AnglesAndInternodes.json`  by a valid `AnglesAndInternodes.json` copied from the geom pipe-> now the visualizer does not crash anymore.
I only tested it for one plant - but I guess it's OK for all.
The point cloud appears as well as segmented point cloud, both can be activated
I could change the colors of the point cloud with the color picker

all looks functional -> **the PR can be merged !!**

_suggestion for improvement_:
-add the 'reset' function for the color of each label of the segmented point cloud
-(Non-segmented point cloud): there is still a bug to tune the transparency.

**Comment by fabfabBesnard** [comment]
**Add-on comment**:
in the main scan list page, available data are not detecting the presence of a segmented point cloud:
image

**Comment by Raphalex46** [comment]
For the scan list icons, I mentionned this in a previous comment :

> This PR will only work correctly with [this PR](https://github.com/romi/romidata/pull/36) merged into romidata.

**Comment by Raphalex46** [comment]
There is a new label icon for the segmented point cloud.

**Pull request merged**
