### PR TITLE
Fix bubble colors bug

### LINKED ISSUE #40: BUG: Bubbles no longer have the right color
Bubbles no longer have the organ color, they're just white. Need to investigate into this.

### PR DESCRIPTION
**Pull request by Raphalex46**
Close #40

### CODE REVIEW

**Comment by fabfabBesnard** [comment]
A bug still persist with the reset function when a pair of organ is selected (through the charts).
If the color of the selected pair is changed and then RESET, the visualizer crashes and the following error message is displayed:
image

Note that when organ color of the entire plant is changed, the bug does not happen

**Comment by Raphalex46** [comment]
Looks like I didn't test this enough. It will be fixed tomorrow.

**Review by fabfabBesnard — CHANGES_REQUESTED** [review]
fix the remaining bug with reset function

**Comment by Raphalex46** [comment]
Should be fixed

**Comment by fabfabBesnard** [comment]
ok, bug on resetting colors is fixed !

**Review by fabfabBesnard — APPROVED** [review]
this PR can be merged

**Pull request merged**
